/* Generated By:JavaCC: Do not edit this line. ObjParserConstants.java */
package com.quew8.geng3d.objparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ObjParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMENT = 3;
  /** RegularExpression Id. */
  int EOL = 4;
  /** RegularExpression Id. */
  int SLASH = 6;
  /** RegularExpression Id. */
  int VERTEX = 7;
  /** RegularExpression Id. */
  int TEX_COORD = 8;
  /** RegularExpression Id. */
  int NORMAL = 9;
  /** RegularExpression Id. */
  int FACE = 10;
  /** RegularExpression Id. */
  int LETTER = 11;
  /** RegularExpression Id. */
  int DIGIT = 12;
  /** RegularExpression Id. */
  int NUM_FLOAT = 13;
  /** RegularExpression Id. */
  int NUM_INT = 14;
  /** RegularExpression Id. */
  int WORD = 15;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int COMMENT_LINE = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<COMMENT>",
    "<EOL>",
    "<token of kind 5>",
    "\"/\"",
    "\"v\"",
    "\"vt\"",
    "\"vn\"",
    "\"f\"",
    "<LETTER>",
    "<DIGIT>",
    "<NUM_FLOAT>",
    "<NUM_INT>",
    "<WORD>",
  };

}
